### ISSUE TITLE
nom des forum sans ID

### ISSUE THREAD

**Issue by Laurentbmw** [phpbb-fr-com/seoregression#1]
bonjour, 
j'ai utilisé une extension d'url Re Writting durant 15 jours sur mon forum en php3.2.2, que j'ai désactivé suite à quelques bug mineurs

J'ai installé SEO Regression qui fonctionne parfaitement sauf pour le point suivant :

j'ai un soucis pour la redirection des forum, en effet, l'extension que j'avais utilisé utilisait un système de cache pour ne pas afficher l'ID du forum en fin d'url, par exemple ;

`https://www.bmw-serie3.com/phpbb3/devenir-donateur-aider-forum.html
`
renvoyai vars :

`https://www.bmw-serie3.com/phpbb3/devenir-donateur-aider-forum-f378.html
`
Les url indexées par google sont celle dans l'ID du forum.

SI je rentre l'url ré écrite avec l'ID du forum, l'extension SEO Regression renvoit bien vers le bon forum, en ce sens on peut dire qu'elle fait le job.

Sauf que comme google à indexés les url sans les ID, celle ci ne fonctionne donc plus, car je pense que l'extension ne sait pas ou rediriger pour le coup.

Par contre, dans le cache de l'extension que j'avais utilisé pour le ré écriture j'ai cette ligne là :

`$forum_urls = array ( 3 => 'pour-les-nouveaux-membres', 4 => 'regles-du-forum', 5 => 'presentation-des-membres', 34 => 'les-autres-serie3', 35 => 'e21-e30-e36', 42 => 'discussion-generale', 43 => 'forums-prives', 44 => 'administration', 45 => 'news-et-infos-generales-automobile', 52 => 'divers', 53 => 'petites-annonces', 66 => 'autres-bmw', 67 => 'detente', 68 => 'sondages', 69 => 'le-forum', 70 => 'corbeille-du-forum', 73 => 'autres-marques', etc.... );`

est ce que je peux réutiliser ces info à placer quelques part afin de renseigner l'extension SEO Regression sur les ID des forum?

Merci par avance

**Comment by Zoddo** [comment]
Bonjour,

En copiant le fichier `phpbb_cache.php` de l'extension de réécriture à la place de [celui-ci](https://github.com/phpbb-fr-com/seoregression/blob/master/includes/phpbb_cache.php), ça devrait fonctionner. (il peut y avoir besoin de remplacer `$forum_urls = ` par `$this->cache_config['forum'] = ` si ça ne fonctionne pas)

On a jamais testé cette configuration avec cette extension, donc c'est à vérifier.

Par ailleurs, lorsque vous êtes sur la deuxième page d'un forum, quel est l'URL réécrite ? Il est possible qu'il y ait besoin de faire une légère adaptation dans l'extension.

**Comment by Laurentbmw** [comment]
en fait dans l'extension ce n'est pas un fichier `phpbb_cache.php`, 
mais un fichier `config_runtime.php` (qui contient les info de corrélation entre nom de forum et ID) qui est placer dans un dossier se nommant `/cache`.

ensuite, à la racine de l'extension dans le fichier core.php j'ai les lignes suivantes qui s'y rapporte : 

> // Caching config
> 		define('PHPBB_SEO_USU_ROOT_DIR', rtrim(dirname(realpath(__FILE__)), '\\/') . '/');
> 		$this->seo_opt['cache_folder'] = PHPBB_SEO_USU_ROOT_DIR . 'cache/'; // where the cache file is stored 
> 		$this->seo_opt['topic_type'] = array(); // do not change
> 		$this->cache_config['cache_enable'] = true; // do not change
> 		$this->cache_config['rem_ids'] = $this->seo_opt['rem_ids']; // do not change, set up above
> 		$this->cache_config['file'] = $this->seo_opt['cache_folder'] . 'config.runtime.' . $this->php_ext;
> 		$this->cache_config['cached'] = false; // do not change
> 		$this->cache_config['forum_urls'] = array(); // do not change
> 		$this->cache_config['forum'] = array(); // do not change
> 		// $this->cache_config['topic'] = array(); // do not change
> 		$this->cache_config['settings'] = array(); // do not change

**Comment by Falcon67** [comment]
Salut,

Essai en copiant ton contenu

`3 => 'pour-les-nouveaux-membres', 4 => 'regles-du-forum', 5 => 'presentation-des-membres', 34 => 'les-autres-serie3', 35 => 'e21-e30-e36', 42 => 'discussion-generale', 43 => 'forums-prives', 44 => 'administration', 45 => 'news-et-infos-generales-automobile', 52 => 'divers', 53 => 'petites-annonces', 66 => 'autres-bmw', 67 => 'detente', 68 => 'sondages', 69 => 'le-forum', 70 => 'corbeille-du-forum', 73 => 'autres-marques'`

entre les parenthèses de `$this->cache_config['forum'] = array ();`

**Comment by Laurentbmw** [comment]
Merci pour ton aide, 
Malheureusement cela ne fonctionne pas, 

`La page demandé n'a pas été trouvé`

il doit pourtant bien y avoir une solution depuis ces informations d'automatiser l'ajout de l'ID derrière le nom du forum sans avoir à me retaper mes 57 forum à inclure en dur dans l'extension comme ceci :+1: 

`array('pattern' => 'pour-les-nouveaux-membres\.html', 'replacement' => 'viewforum.php?f=3'),`

**Comment by Falcon67** [comment]
L'extension est basé sur la prémod SEO sous phpBB 3.0 et non en fonction d'une autre extension, il peut donc y avoir des adaptations à faire.

Que contient ton fichier `config_runtime.php` ?

**Comment by Laurentbmw** [comment]
```php
<?php
/**
* phpBB SEO
* www.phpBB-SEO.org
* @package phpBB SEO USU
*/
if (!defined('IN_PHPBB')) {
	exit;
}
$settings = array ( 'url_rewrite' => true, 'modrtype' => 3, 'sql_rewrite' => false, 'profile_inj' => true, 'profile_vfolder' => true, 'profile_noids' => true, 'rewrite_usermsg' => true, 'rem_sid' => true, 'rem_hilit' => true, 'rem_small_words' => false, 'virtual_folder' => false, 'virtual_root' => false, 'cache_layer' => true, 'rem_ids' => true, 'redirect_404_forum' => true, 'redirect_404_topic' => true, 'copyrights' => array ( 'img' => true, 'txt' => '', 'title' => '', ), 'zero_dupe' => array ( 'on' => true, 'strict' => false, 'post_redir' => 'all', ), );
$forum_urls = array ( 3 => 'pour-les-nouveaux-membres', 4 => 'regles-du-forum', 5 => 'presentation-des-membres', 34 => 'les-autres-serie3', 35 => 'e21-e30-e36', 42 => 'discussion-generale', 43 => 'forums-prives', 44 => 'administration', 45 => 'news-et-infos-generales-automobile', 52 => 'divers', 53 => 'petites-annonces', 66 => 'autres-bmw', 67 => 'detente', 68 => 'sondages', 69 => 'le-forum', 70 => 'corbeille-du-forum', 73 => 'autres-marques', 74 => 'espace-moderation', 79 => 'rencontres-entre-membres', 80 => 'planifications-des-rencontres', 81 => 'compte-rendu-des-rencontres', 88 => 'jeux-et-concours', 89 => 'concours-saisonniers', 90 => 'vos-passions', 100 => 'm3-e30-e36', 106 => 'jeux', 108 => 'bon-plans-d-achat', 111 => 'forum-dedie-a-la-serie-3-type-e90', 112 => 'votre-serie-3-diesel-type-e90', 113 => 'e90-diesel-berline-4-portes', 114 => 'e91-diesel-touring-5-portes', 115 => 'e92-diesel-coupe-2-portes', 116 => 'e93-diesel-cabrio-2-portes', 117 => 'votre-serie-3-essence-type-e90', 118 => 'e90-essence-berline-4-portes', 119 => 'e91-essence-touring-5-portes', 121 => 'e92-essence-coupe-2-portes', 122 => 'e93-essence-cabrio-2-portes', 123 => 'm3-e90', 124 => 'guide-d-achat-et-fiches-techniques-de-votre-serie-3-type-e90', 125 => 'la-cote-des-options-e9x', 126 => 'teintes-exterieures-e9x', 127 => 'teintes-interieures-e9x', 128 => 'inserts-e9x', 129 => 'jantes-officielles-e9x', 130 => 'motorisation-e9x', 146 => 'la-serie3-type-e90', 147 => 'discussion-generale-e9x', 148 => 'photos-videos-liens-e9x', 150 => 'forum-dedie-a-la-serie-3-serie-4-type-f3x', 151 => 'votre-serie-3-serie-4-diesel-type-f3x', 152 => 'votre-serie-3-serie-4-essence-type-f3x', 153 => 'guide-d-achat-et-fiches-techniques-de-votre-serie3-serie-4-type-f3x', 158 => 'la-serie3-serie-4-type-f3x', 159 => 'f30-diesel-berline-4-portes', 160 => 'f31-diesel-touring-5-portes', 161 => 'f32-diesel-coupe-2-portes', 162 => 'f33-diesel-cabrio-2-portes', 163 => 'f30-essence-berline-4-portes', 164 => 'f31-essence-touring-5-portes', 165 => 'f32-essence-coupe-2-portes', 166 => 'f33-essence-cabrio-2-portes', 167 => 'm3-f80-m4', 168 => 'la-cote-des-options-f3x', 169 => 'teintes-exterieures-f3x', 170 => 'teintes-interieures-f3x', 171 => 'inserts-f3x', 172 => 'jantes-officielles-f3x', 173 => 'motorisation-f3x', 185 => 'discussion-generale-f3x', 186 => 'photos-videos-liens-f3x', 188 => 'partenaires-officiels-de-bmw-serie3-com', 190 => 'partenaires', 196 => 'suntech', 197 => 'team-bs', 198 => 'forum-prive-shiftech-engineering', 201 => 'fiches-techniques-e9x', 202 => 'fiches-techniques-f3x', 203 => 'pieces-performances-pour-e9x', 204 => 'pieces-performances-pour-f3x', 206 => 'rb-automotive', 207 => 'shinearama-co-uk', 209 => 'bmw-serie3-com-sur-facebook', 211 => 'technique-serie3-serie-4-type-f3x', 212 => 'moteur-f3x', 213 => 'liaison-au-sol-f3x', 214 => 'exterieur-f3x', 215 => 'interieur-f3x', 216 => 'pannes-problemes-et-entretien-f3x', 218 => 'tutos-f3x', 219 => 'technique-serie-3-type-e90', 220 => 'moteur-e9x', 221 => 'liaison-au-sol-e9x', 222 => 'exterieur-e9x', 223 => 'interieur-e9x', 224 => 'pannes-problemes-et-entretien-e9x', 225 => 'tutos-e9x', 226 => 'nouveautes-automobiles-bmw', 227 => 'nouveautes-et-actualites-de-la-serie3-et-serie4', 228 => 'nouveautes-et-actualites-des-autres-bmw', 229 => 'achats', 230 => 'ventes', 231 => 'achats-recherches', 232 => 'achats-groupes', 233 => 'ventes-vehicules', 234 => 'vente-de-pieces-detachees-accessoires-jantes', 235 => 'forum-dedie-a-la-serie-3-type-e46', 236 => 'votre-serie-3-diesel-type-e46-e46', 237 => 'votre-serie-3-essence-type-e46-e46-5-m3', 238 => 'guide-d-achat-et-fiches-techniques-serie-3-type-e46', 239 => 'technique-serie-3-type-e46-e46-5-m3', 240 => 'la-serie-3-type-e46-e46-5-m3', 241 => 'e46-diesel-berline-4-portes', 242 => 'e46-diesel-coupe-3-portes', 243 => 'e46-diesel-touring-5-portes', 244 => 'e46-diesel-cabrio-2-portes', 245 => 'e46-5-diesel-compact', 246 => 'e46-essence-berline-4-portes', 247 => 'e46-essence-touring-5-portes', 248 => 'e46-essence-coupe-3-portes', 249 => 'e46-essence-cabrio-2-portes', 250 => 'e46-5-essence-compact', 251 => 'm3-e46', 252 => 'fiches-techniques-e46', 253 => 'la-cote-des-options-e46', 254 => 'teintes-exterieures-e46', 255 => 'teintes-interieures-e46', 256 => 'inserts-e46', 257 => 'jantes-officielles-e46', 258 => 'motorisations-e46', 259 => 'moteur-e46', 260 => 'liaison-au-sol-e46', 261 => 'exterieur-e46', 262 => 'interieur-e46', 263 => 'pannes-problemes-et-entretien-e46', 264 => 'tutos-e46', 265 => 'discussion-generale-e46', 266 => 'photos-videos-liens-e46', 267 => 'abcoding', 268 => 'mg-connex', 269 => 'glastint-issy', 270 => 'pack-led-com', 311 => 'm-tech', 312 => 'bug-ou-remarque-et-discussions-generale-sur-le-forum', 313 => 'tutos', 315 => 'ledperf-com', 316 => 'krazy-light-com', 317 => 'la-boutique-bmw-serie3-com', 318 => 'f34-diesel-gt-5-portes', 319 => 'f34-essence-gt-5-portes', 320 => 'autoradiofactory-com', 321 => 'concours', 322 => 'votes-concours', 323 => 'shiftech-engineering', 324 => 'performance-store', 325 => 'accessoires-bmw-fr', 328 => 'corbeille-divers', 329 => 'corbeille-partenaires', 330 => 'gestion-partenaires', 331 => 'detailing-soins-et-lavage-automobile', 332 => 'les-etapes-et-techniques-de-detailing', 333 => 'lavage', 334 => 'les-shampoings', 337 => 'decontamination', 341 => 'correction', 344 => 'lustrage', 347 => 'protection', 351 => 'entretien-interieur-et-habitacle', 352 => 'les-produits-pour-l-entretien-interieur-et-vitres', 353 => 'les-produits-pour-l-entretien-du-cuir', 354 => 'questions-et-discussions-sur-l-entretien-interieur', 355 => 'les-accessoires', 361 => 'vos-realisations', 362 => 'vos-realisations-detailling', 363 => 'votre-materiel', 364 => 'lexiques-e-shop-faq', 365 => 'dilution-des-produits', 366 => 'les-e-shop', 369 => 'faq', 371 => 'bmw-bms-mantes-buchelay', 372 => 'espace-donateurs', 374 => 'coding-diagnostique-retrofit', 375 => 'f36-diesel-gc-5-portes', 377 => 'f36-essence-gc-5-portes', 378 => 'devenir-donateur-et-aider-le-forum', 379 => 'bretagne-polish-auto', 382 => 'autre-bmw', 383 => 'entretien-exterieur', 384 => 'discussion-general-sur-le-detailing', 385 => 'moderation-des-membres', 387 => 'rs-car-design', 388 => 'bons-plans-garages', 389 => 'alsace', 390 => 'bas-rhin', 391 => 'haut-rhin', 392 => 'aquitaine', 393 => 'dordogne', 394 => 'gironde', 395 => 'landes', 396 => 'lot-et-garonne', 397 => 'pyrenees-atlantiques', 398 => 'auvergne', 399 => 'allier', 400 => 'cantal', 401 => 'haute-loire', 402 => 'puy-de-dome', 403 => 'basse-normandie', 404 => 'calvados', 405 => 'manche', 406 => 'orne', 407 => 'bourgogne', 408 => 'cote-d-or', 409 => 'nievre', 410 => 'saone-et-loire', 411 => 'yonne', 412 => 'bretagne', 413 => 'cotes-d-armor', 414 => 'finistere', 415 => 'morbihan', 416 => 'ille-et-vilaine', 417 => 'centre', 418 => 'cher', 419 => 'eure-et-loire', 420 => 'indre', 421 => 'indre-et-loire', 422 => 'loir-et-cher', 423 => 'loiret', 424 => 'champagne-ardenne', 425 => 'ardennes', 426 => 'aube', 427 => 'marne', 428 => 'haute-marne', 429 => 'corse', 430 => 'corse-du-sud-2a', 431 => 'haute-corse-2b', 432 => 'franche-comte', 433 => 'doubs', 434 => 'jura', 435 => 'haute-saone', 436 => 'territoire-de-belfort', 437 => 'haute-normandie', 438 => 'eure', 439 => 'seine-maritime', 440 => 'ile-de-france', 441 => 'paris', 442 => 'seine-et-marne', 443 => 'yvelines', 444 => 'essone', 445 => 'hauts-de-seine', 446 => 'seine-saint-denis', 447 => 'val-de-marne', 448 => 'val-d-oise', 449 => 'languedoc-roussillon', 450 => 'aude', 451 => 'gard', 452 => 'lozere', 453 => 'pyrenees-orientales', 454 => 'limousin', 455 => 'correze', 456 => 'creuse', 457 => 'haute-vienne', 458 => 'lorraine', 459 => 'meurthe-et-moselle', 460 => 'meuse', 461 => 'moselle', 462 => 'vosges', 463 => 'midi-pyrenees', 464 => 'ariege', 465 => 'aveyron', 466 => 'gers', 467 => 'lot', 468 => 'hautes-pyrenees', 469 => 'tarn', 470 => 'tarn-et-garonne', 471 => 'nord-pas-de-calais', 472 => 'nord', 473 => 'pas-de-calais', 474 => 'pays-de-la-loire', 475 => 'loire-atlantique', 476 => 'maine-et-loire', 477 => 'mayenne', 478 => 'sarthe', 479 => 'vendees', 480 => 'picardie', 481 => 'aisne', 482 => 'oise', 483 => 'somme', 484 => 'poitou-charentes', 485 => 'charente', 486 => 'charente-maritime', 487 => 'deux-sevres', 488 => 'viennes', 489 => 'provence-alpes-cote-d-azur', 490 => 'alpes-de-haute-provence', 491 => 'hautes-alpes', 492 => 'alpes-maritimes', 493 => 'var', 494 => 'vaucluse', 495 => 'rhone-alpes', 496 => 'ain', 497 => 'ardeche', 498 => 'drome', 499 => 'isere', 500 => 'loire', 501 => 'rhone', 502 => 'savoie', 503 => 'haute-savoie', 504 => 'regions-d-outre-mer', 505 => 'guadeloupe', 506 => 'martinique', 507 => 'guyane', 508 => 'la-reunion', 509 => 'mayotte', 510 => 'belgique', 511 => 'bruxelles', 512 => 'flandre', 513 => 'wallonie', 514 => 'herault', 515 => 'patrolline', 516 => 'all-custom', 518 => 'corbeille-annonces', 520 => 'haute-garonne', 521 => 'ledperf', 522 => 'corbeilles-tutos', 523 => 'bouches-du-rhone', 524 => 'forum-bmwserie5-com', );

```

**Comment by Falcon67** [comment]
Donc pour la partie `$forum_urls = array ( ..........) ` à remplacer par `$this->cache_config['forum'] = array ( ..........) ` et à mettre dans https://github.com/phpbb-fr-com/seoregression/blob/master/includes/phpbb_cache.php

Le format est le même que dans phpBB SEO 3.0

**Comment by Zoddo** [comment]
@Falcon67 On a besoin de faire une petite adaptation sur l'extension.

L'extension fonctionne avec les forums sans ID en mode dossier virtuel. Or, dans ce cas, ce ne sont pas des dossiers virtuel (voir le .html à la fin de ses URL de forum).

@Laurentbmw As-tu un exemple d'URL réécrite sur la deuxième page (par exemple) d'un forum ?

**Comment by Laurentbmw** [comment]
en fait je n'avais pas activé l'option des dossiers virtuels, donc mes url de forum ont toutes la même syntaxes peu importe leur niveau de pages : 
https://www.bmw-serie3.com/nom-du-forum.html

qui elle même renvoyait vers :
https://www.bmw-serie3.com/nom-du-forum-f[id].html

@Falcon67 : J'ai essayé comme tu me l'a conseillé

>  Donc pour la partie $forum_urls = array ( ..........) à remplacer par $this->cache_config['forum'] = array ( ..........) et à mettre dans https://github.com/phpbb-fr-com/seoregression/blob/master/includes/phpbb_cache.php

Mais sans succès, à moins qu'il y ait un opération particulière lorsque le fichier /phpbb_cache est modifié.

Voici ce que je faisais :

- Modification du fichier comme conseillé
- envoi sur le ftp
- vidage cache forum via acp

Mais pas de changement

**Comment by Zoddo** [comment]
@Laurentbmw Je vais tenter une modification dans l'après-midi pour supporter ces URLs de forum ;)

**Comment by Zoddo** [comment]
Bon, en fait, j'avais pas remarqué que la reconnaissance des forums sans ID était totalement cassé depuis la 1.2.0.

Poke @Skouat si tu passes par ici.  
Une valeur qui est assigné dans le tableau `$id` juste avant d'être écrasé, y'a pas un petit problème ?
```php
// No ID, we try to find a forum ID
if (empty($id['id']))
{
	$forum_info = $this->get_forums_info($uri);

	if (isset($forum_info['id']))
	{
		$id['id'] = $forum_info['id'];
		$id = $this->get_higher_id($this->get_id($uri, 'paginate', $fail_check_seo_params == 0), 'num_page');
	}
}
```
Et honettement, je vois pas à quel moment il va chercher la règle `noids`. On dirait une modification qui n'a jamais été terminée.

**Comment by Laurentbmw** [comment]
Juste pour info @Zoddo, en fait les secondes page des forum ont cette forme :  
`phpbb3/e92-essence-coupe-2-portes/page25.html`

**Comment by Skouat** [comment]
@Zoddo 

> Et honettement, je vois pas à quel moment il va chercher la règle `noids`. On dirait une modification qui n'a jamais été terminée.

Lignes [228-237](https://github.com/phpbb-fr-com/seoregression/blob/master/event/listener.php#L228-L237) par exemple ?

Dans un contexte d'URL sans ID, si aucune règle n'est trouvée dans le cache alors c'est qu'il n'y a plus de solution envisageable car sans ID difficile de trouver une correspondance de forum.
Donc là règle fonction comme attendue ou sinon je ne comprend pas ta remarque

@Laurentbmw 
Donc rien de bien particulier, c'est ainsi que c'est défini par défaut au niveau de la règle "noids".

**Comment by Zoddo** [comment]
Je vois toujours pas comment ça récupères la règle noids.

**Comment by Skouat** [comment]
@Zoddo => [Dans cette boucle](https://github.com/phpbb-fr-com/seoregression/blob/master/event/listener.php#L366-L379)

En fait le bug provient du fait que pour limiter les faux positifs je supprime la partie de l'URL trouvée dans le fichier de cache.
Or, dans le cas de @Laurentbmw, une fois le nom du forum supprimé il ne reste donc plus que `/.html` comme nouvelle base URI. D'où le bug.

Il faudrait ajouter un contrôle de paramètre afin de voir si l'option `virtual_folder` est à `true` ou `false`.

**Comment by Laurentbmw** [comment]
en tout cas merci pour les effort, j'espère vraiment que vous trouverez une solution, car du coup les 404 explosent.

**Comment by Zoddo** [comment]
@Laurentbmw En soit, l'extension est censé rediriger correctement tous les sujets. Seules les URLs de forums ne sont pas redirigés, ce qui reste un problème "minime".

**Comment by Zoddo** [comment]
@Laurentbmw En soit, l'extension est censé rediriger correctement tous les sujets. Seules les URLs de forums ne sont pas redirigés, ce qui reste un problème "minime".

@Skouat tu connais mieux ton code que moi. Je te laisse regarder ?

**Comment by Laurentbmw** [comment]
Oui pour les sujets c'est impec, 
Concernant les forum, cela m'a généré plus de 500 pages en 404 (il y a des forum avec beaucoup de pages)

Pas sur que cela soit si minime pour notre très cher google :)

**Comment by Falcon67** [comment]
@Zoddo et @Skouat > [Ici](https://github.com/phpbb-fr-com/seoregression/blob/master/event/listener.php#L55) il ne faudrait pas plutôt `if (!empty($this->cache_config['forum']))` ? En fait je ne vois pas ou se trouve la correspondance avec `$forum_urls`

**Comment by Skouat** [comment]
@Falcon67 : `$forum_urls` est la variable présente dans le fichier de config de l'extension utilisé par @Laurentbmw. Après de mon avis cet ajout de code ne sert à rien car comme tu l'as indiqué plus haut il suffit de copier/coller le contenue du fichier de conf dans celui déjà présent.

De toute manière le bug de redirection des forum n'a rien à voir avec ce bout de code qui va être supprimé ultérieurement car il n'apporte aucune plus value.

**Comment by Falcon67** [comment]
Ah je me disais bien ;)

Peut être en commançant par vérifier l'URL et la correspondance avec `$this->cache_config['forum']` de **seoregression/includes/phpbb_cache.php** et si pas de résultat seulement on renvoi vers la vérification classique ?

Je pense pouvoir faire des essais début de semaine prochaine.

**Comment by Skouat** [comment]
@Laurentbmw Est-ce que tu peux installer l'archive de la branche [issue-1](https://github.com/phpbb-fr-com/seoregression/archive/issue-1.zip) ?

Ensuite suis les instructions qu'a donné @Falcon67 dans [ce message](https://github.com/phpbb-fr-com/seoregression/issues/1#issuecomment-409609260)
Il faut également faire la même chose avec `$settings` et copier son contenu dans `$this->cache_config['settings'] = array ( )`

A date, ca permettra de rediriger à minima vers la 1ère page du forum.
Par contre, pour la pagination des forums, il faut encore que je trouve une alternative car la pagination vire le `.html` de l'URL.  :(

**Comment by Laurentbmw** [comment]
@Skouat 

impec c'est parfaitement fonctionnel pour les forum sans ID pour la première page!

C'est vraiment top merci.

si tu arrives à gérer la pagination cela sera juste parfait

Merci encore

**Comment by Skouat** [comment]
@Laurentbmw 
Je pense avoir trouvé une solution pour la pagination.
Archive à installer => [issue-1.zip](https://github.com/phpbb-fr-com/seoregression/archive/issue-1.zip)

**Comment by Laurentbmw** [comment]
@Skouat 
Salut.
Cela ne marche pas, 
Peu importe la page, cela renvoi vers l'URL suivante en fonction de l'id du forum 

https://www.bmw-serie3.com/phpbb3/222

Ou 222 est l'id du forum

**Comment by Skouat** [comment]
@Laurentbmw
Peux-tu redonner un expemple d'URL avec pagination et sans pagination ?
As-tu bien recréé le fichier phpbb_cache.php ?

En attendant, réinstalle la précédente version qui fonctionnait mieux.
=> https://github.com/phpbb-fr-com/seoregression/archive/44ab11bf7abbaacde9347e472d1a4ceed4b4c23d.zip

**Comment by Laurentbmw** [comment]
@Skouat  url avec pagination

https://www.bmw-serie3.com/phpbb3/exterieur-e9x/page325.html

URL sans pagination 

https://www.bmw-serie3.com/phpbb3/interieur-e9x.html

Sinon avec la nouvelle archive cela marche tj impec lorsqu'il n'y a pas de pagination. 

Je pense que le numéro de page correspond au start=325

**Comment by Skouat** [comment]
@Laurentbmw 
Je viens de tester et je ne rencontre aucun problème de redirection pour une URL sans ID avec ou sans pagination.

Récupère à nouveau la dernière archive : https://github.com/phpbb-fr-com/seoregression/archive/3cb77594d5e0be050d43b735cb1e918f31b41755.zip

Pour les actions dans le fichier phpbb_cache, y reporter la liste des forums ET la liste des settings.

**Comment by Laurentbmw** [comment]
@Skouat 

en effet, cela fonctionne à présent pour la pagination, 
je n'avais jamais copier la liste des settings, je ne pensais pas que cela jouais sur le fonctionnement.

encore un grand merci tous semble parfaitement fonctionnel à présent.
je ferais un retour d'ici quelques jours afin de bien tous confirmer en fonction de l'evolution de mes 404 dans ma console Google Search

**Comment by Laurentbmw** [comment]
bon, bah après essai, cela fonctionne à merveille pour les forum et la pagnination, mais cela ne fonctionne plus pour les sujet.

si je remet le fichier listener.php de la branche issue_1 je retrouve le bon fonctionnement sur les sujet et les forum, mais je reperd la pagination par rapport à l'archive dont tu m'a donné le lien dans ce message 
https://github.com/phpbb-fr-com/seoregression/issues/1#issuecomment-414129318

@Skouat

**Comment by Skouat** [comment]
@Laurentbmw 
Je viens de corriger. Je pense qu'on est sur la bonne voie.
Le fichier peux-tu tester la dernière version du fichier [listener.php](https://github.com/phpbb-fr-com/seoregression/blob/bd7ad3baccfe53c58e2130a5632c179e02cca39e/event/listener.php) ?

**Comment by Laurentbmw** [comment]
@Skouat 
J'ai fait l'essai sur une 50aine de liens, comprenant des sujet, des sujets avec pagination, des forum, des forum avec pagination, et tout à l'air de rouler impec

j'ai même l'impression que cela fonctionne avec l'option dossier virtuel actif.

Je continu mes test et te tiens au courant, 
en tout cas c'est super merci vraiment, cette extension est génial pour sorti du SEO URL sans avoir des 404 en pagaille et un HTACCESS compliqué
